import { useMemo, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowUpRight, Bath, BedDouble, Car, Check, MapPin, Ruler, Share2, ShieldCheck, X } from 'lucide-react';
import { Link, useLocation, useParams } from 'wouter';
import { useCreateLead, useGetProperty, useListSpecialists } from '@workspace/api-client-react';
import { ErrorState, Lightbox, PageLogo, PublicNav, SectionLabel, SpecialistAvatar, fallbackImages, imageFor, money } from '@/components/signature-ui';

const fallbackProperty = {
  id: 'curated-aurora', title: 'Casa Aurora', location: 'São Paulo', neighborhood: 'Morumbi', category: 'Casa', price: 12800000, area: 640, bedrooms: 5, suites: 4, parking: 6, description: 'Arquitetura de presença, luz natural e privacidade absoluta em um endereço reservado. Casa Aurora foi concebida para que os ambientes se abram ao jardim sem perder o recolhimento que uma residência especial pede.', images: ['/assets/casa_aurora.jpg','/assets/villa_mare.jpg','/assets/penthouse_ibirapuera.jpg'], badges: ['Signature'], featured: true, lpUrl: '', status: 'published',
};

export default function PropertyDetailPage() {
  const { id = '' } = useParams<{ id: string }>();
  const [, setLocation] = useLocation();
  const query = useGetProperty(id, { query: { queryKey: ['/api/properties', id] } });
  const specialistQuery = useListSpecialists();
  const createLead = useCreateLead();
  const [activeImage, setActiveImage] = useState(0);
  const [lightbox, setLightbox] = useState(false);
  const property = query.data || (id.startsWith('curated-') ? fallbackProperty : null);
  const images = useMemo(() => property?.images?.length ? property.images : fallbackImages, [property]);
  const specialist = specialistQuery.data?.[0];

  function submitLead(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    createLead.mutate({ data: { name: String(form.get('name') || ''), email: String(form.get('email') || ''), phone: String(form.get('phone') || ''), propertyId: property?.id || id, propertyTitle: property?.title || '', status: 'new', source: 'property-page', note: String(form.get('message') || 'Solicitou uma visita pelo portal.') } }, { onSuccess: () => event.currentTarget.reset() });
  }

  if (query.isLoading && !property) return <div className="signature-shell min-h-[100dvh] pt-32"><PublicNav /><div className="mx-auto max-w-[1280px] px-5 md:px-10"><div className="skeleton aspect-[16/7] rounded-3xl" /><div className="mt-6 grid gap-6 md:grid-cols-2"><div className="skeleton h-52 rounded-3xl" /><div className="skeleton h-52 rounded-3xl" /></div></div></div>;
  if (query.isError && !property) return <div className="signature-shell min-h-[100dvh] pt-32"><PublicNav /><div className="mx-auto max-w-3xl px-5 py-24"><ErrorState onRetry={() => query.refetch()} /></div></div>;
  if (!property) return <div className="signature-shell min-h-[100dvh] pt-32"><PublicNav /><div className="mx-auto max-w-3xl px-5 py-24"><ErrorState onRetry={() => setLocation('/')} /></div></div>;

  const specs = [{ icon: Ruler, value: `${property.area} m²`, label: 'Área construída' }, { icon: BedDouble, value: `${property.bedrooms}`, label: 'Quartos' }, { icon: Bath, value: `${property.suites}`, label: 'Suítes' }, { icon: Car, value: `${property.parking}`, label: 'Vagas' }];
  return <div className="signature-shell min-h-[100dvh] text-[#f5f2e9]"><PublicNav /><main className="mx-auto max-w-[1280px] px-5 pb-24 pt-32 md:px-10 md:pt-40">
    <div className="mb-7 flex items-center justify-between"><Link href="/" className="flex items-center gap-2 text-xs text-[#9a9a9a] hover:text-[#e8c766]" data-testid="link-back-catalog"><ArrowLeft size={15} /> Voltar à seleção</Link><div className="flex gap-2"><button onClick={() => navigator.clipboard?.writeText(window.location.href)} className="flex h-10 items-center gap-2 rounded-full border border-white/10 px-4 text-xs text-[#c9c9c9] hover:border-[#d4af37]" data-testid="button-share-property"><Share2 size={14} /> Compartilhar</button><button onClick={() => setLocation('/')} className="flex h-10 w-10 items-center justify-center rounded-full border border-white/10 text-[#d4af37]" aria-label="Fechar" data-testid="button-close-property"><X size={15} /></button></div></div>
    <section className="grid gap-3 md:grid-cols-[1.45fr_.55fr] md:grid-rows-2"><button onClick={() => setLightbox(true)} className="group relative row-span-2 overflow-hidden rounded-3xl text-left" data-testid="button-open-gallery"><img src={images[0]} alt={property.title} className="h-full min-h-[330px] w-full object-cover transition duration-700 group-hover:scale-[1.025]" /><span className="absolute bottom-5 left-5 rounded-full bg-black/55 px-4 py-2 text-xs text-white backdrop-blur">Abrir galeria · {images.length} imagens</span></button><button onClick={() => { setActiveImage(1 % images.length); setLightbox(true); }} className="hidden overflow-hidden rounded-3xl md:block" data-testid="button-gallery-thumbnail-1"><img src={images[1 % images.length]} alt="" className="h-full w-full object-cover transition duration-700 hover:scale-[1.04]" /></button><button onClick={() => { setActiveImage(2 % images.length); setLightbox(true); }} className="hidden overflow-hidden rounded-3xl md:block" data-testid="button-gallery-thumbnail-2"><img src={images[2 % images.length]} alt="" className="h-full w-full object-cover transition duration-700 hover:scale-[1.04]" /></button></section>
    <section className="grid gap-10 py-12 lg:grid-cols-[1fr_380px] lg:gap-20"><div><div className="flex flex-wrap gap-2">{(property.badges || []).map((badge) => <span key={badge} className="rounded-full bg-[#d4af37] px-3 py-1 text-[9px] font-bold uppercase tracking-[.14em] text-black">{badge}</span>)}<span className="rounded-full border border-white/15 px-3 py-1 text-[9px] uppercase tracking-[.14em] text-[#9a9a9a]">{property.category}</span></div><h1 className="serif mt-5 text-5xl leading-[.95] text-white md:text-7xl" data-testid="text-property-title">{property.title}</h1><p className="mt-4 flex items-center gap-2 text-sm text-[#9a9a9a]"><MapPin size={16} className="text-[#d4af37]" />{property.neighborhood}, {property.location}</p><p className="mt-9 max-w-2xl text-base leading-8 text-[#c9c9c9]" data-testid="text-property-description">{property.description}</p><div className="my-10 gold-line max-w-2xl" /><div className="grid grid-cols-2 gap-y-8 sm:grid-cols-4">{specs.map(({ icon: Icon, value, label }) => <div key={label} className="flex gap-3"><Icon size={22} className="text-[#d4af37]" strokeWidth={1.4} /><div><p className="text-lg text-white">{value}</p><p className="mt-1 text-[11px] text-[#7a7a7a]">{label}</p></div></div>)}</div><div className="mt-12"><SectionLabel>O que torna este endereço especial</SectionLabel><div className="grid gap-x-6 gap-y-4 sm:grid-cols-2">{['Arquitetura autoral e materiais naturais', 'Integração generosa entre interior e jardim', 'Privacidade em rua tranquila e arborizada', 'Acabamentos escolhidos para durar', 'Paisagismo assinado', 'Segurança e acesso controlado'].map((item) => <p key={item} className="flex items-center gap-3 text-sm text-[#c9c9c9]"><Check size={16} className="text-[#d4af37]" />{item}</p>)}</div></div><div className="map-grid relative mt-12 h-56 overflow-hidden rounded-3xl border border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_55%_45%,transparent_0,rgba(10,10,10,.2)_60%,rgba(10,10,10,.7)_100%)]" /><div className="absolute left-[56%] top-[43%]"><span className="absolute -inset-3 animate-ping rounded-full bg-[#d4af37]/30" /><span className="relative flex h-8 w-8 items-center justify-center rounded-full border border-[#f4e5a8] bg-[#d4af37] text-black"><MapPin size={15} /></span></div><p className="absolute bottom-4 left-4 mono-label text-[#9a9a9a]">Localização aproximada · {property.neighborhood}</p></div></div>
      <aside className="lg:sticky lg:top-28 lg:self-start"><div className="rounded-3xl border border-[#d4af37]/30 bg-[#161616] p-6 md:p-8"><p className="mono-label text-[#9a9a9a]">Valor de referência</p><p className="mt-2 text-3xl font-bold text-[#e8c766]" data-testid="text-property-price">{money(property.price)}</p><div className="my-6 gold-line" /><p className="mb-4 text-sm text-[#c9c9c9]">Conheça este imóvel em uma visita reservada.</p><form onSubmit={submitLead} className="space-y-3" data-testid="form-property-lead"><input name="name" required placeholder="Seu nome" className="h-12 w-full rounded-xl border border-white/15 bg-black/20 px-4 text-sm text-white outline-none focus:border-[#d4af37]" data-testid="input-lead-name" /><input name="email" required type="email" placeholder="Seu email" className="h-12 w-full rounded-xl border border-white/15 bg-black/20 px-4 text-sm text-white outline-none focus:border-[#d4af37]" data-testid="input-lead-email" /><input name="phone" required placeholder="WhatsApp" className="h-12 w-full rounded-xl border border-white/15 bg-black/20 px-4 text-sm text-white outline-none focus:border-[#d4af37]" data-testid="input-lead-phone" /><textarea name="message" placeholder="Como podemos preparar sua visita?" className="min-h-20 w-full resize-none rounded-xl border border-white/15 bg-black/20 p-4 text-sm text-white outline-none focus:border-[#d4af37]" data-testid="input-lead-message" /><button type="submit" className="metal-button flex h-13 w-full items-center justify-center gap-2 rounded-full text-xs font-bold" data-testid="button-submit-lead">{createLead.isPending ? 'Enviando solicitação' : 'Agendar visita privada'} <ArrowUpRight size={16} /></button>{createLead.isSuccess && <p className="flex items-center gap-2 text-xs text-[#7acb8e]" data-testid="status-lead-success"><ShieldCheck size={14} /> Recebemos seu pedido. Retornaremos em breve.</p>}{createLead.isError && <p className="text-xs text-[#e0554a]" data-testid="status-lead-error">Não foi possível enviar. Tente novamente.</p>}</form></div>{specialist && <div className="mt-5 rounded-3xl border border-white/10 bg-[#121212] p-5"><p className="mono-label mb-4 text-[#d4af37]">Seu especialista</p><div className="flex items-center gap-3"><SpecialistAvatar specialist={specialist} size="sm" /><div><p className="text-sm text-white">{specialist.name}</p><p className="text-[11px] text-[#7a7a7a]">{specialist.role}</p></div></div><a href={`https://wa.me/${specialist.whatsapp}`} className="mt-4 flex h-11 items-center justify-center rounded-full border border-[#d4af37]/40 text-xs text-[#e8c766] hover:bg-[#d4af37]/10" data-testid="link-specialist-whatsapp">Falar pelo WhatsApp</a></div>}</aside>
    </section></main>{lightbox && <Lightbox images={images} active={activeImage} onClose={() => setLightbox(false)} onPrev={() => setActiveImage((activeImage - 1 + images.length) % images.length)} onNext={() => setActiveImage((activeImage + 1) % images.length)} />}</div>;
}