import { useState } from "react";
import { Waves, Dumbbell, Flower2, Flame, Laptop, Package, CircleCheck, Trees, Bike, CarFront, ShieldCheck, Utensils, Wine, PawPrint, Baby, Gamepad2, Music, Sun, Sofa, Building2, Accessibility, Droplets, ConciergeBell, Volleyball } from "lucide-react";
export const featureIcons = [
  {id:"check",label:"Geral",Icon:CircleCheck},{id:"pool",label:"Piscina / sky pool",Icon:Waves},{id:"gym",label:"Academia",Icon:Dumbbell},{id:"spa",label:"Spa / bem-estar",Icon:Flower2},{id:"sauna",label:"Sauna",Icon:Flame},{id:"coworking",label:"Coworking",Icon:Laptop},{id:"lockers",label:"Lockers / entregas",Icon:Package},{id:"garden",label:"Jardim / natureza",Icon:Trees},{id:"bike",label:"Bicicletário",Icon:Bike},{id:"parking",label:"Garagem",Icon:CarFront},{id:"security",label:"Segurança",Icon:ShieldCheck},{id:"gourmet",label:"Gourmet / churrasqueira",Icon:Utensils},{id:"party",label:"Salão de festas",Icon:Wine},{id:"pet",label:"Pet",Icon:PawPrint},{id:"kids",label:"Infantil",Icon:Baby},{id:"games",label:"Jogos",Icon:Gamepad2},{id:"music",label:"Música",Icon:Music},{id:"terrace",label:"Terraço / solário",Icon:Sun},{id:"lounge",label:"Lounge",Icon:Sofa},{id:"building",label:"Edifício",Icon:Building2},{id:"accessible",label:"Acessibilidade",Icon:Accessibility},{id:"water",label:"Água",Icon:Droplets},{id:"concierge",label:"Portaria",Icon:ConciergeBell},{id:"sports",label:"Esportes",Icon:Volleyball},
];
export const getFeatureIcon = (id?:string) => featureIcons.find(f=>f.id===id)?.Icon || CircleCheck;
export function FeatureIconPicker({value,onChange}:{value:string;onChange:(id:string)=>void}) {
  const [search,setSearch]=useState("");
  return <fieldset className="space-y-3"><legend className="text-sm">Ícone da característica</legend><input aria-label="Buscar ícone" className="w-full rounded-xl border border-white/20 bg-[#171717] p-3 text-sm text-white" placeholder="Buscar na biblioteca de ícones" value={search} onChange={e=>setSearch(e.target.value)}/><div className="grid max-h-64 grid-cols-3 gap-2 overflow-y-auto p-1">{featureIcons.filter(f=>f.label.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR"))).map(f=><button key={f.id} type="button" aria-pressed={(value||"check")===f.id} onClick={()=>onChange(f.id)} className={`flex flex-col items-center gap-2 rounded-xl border p-3 text-center text-xs ${value===f.id?"border-primary bg-primary/15 text-primary":"border-white/20 text-white"}`}><f.Icon size={23} strokeWidth={1.5}/>{f.label}</button>)}</div></fieldset>;
}
